package com.example.SimpleSpringWebApp;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import antlr.collections.List;

@Controller // This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepo userRepository;

  @Autowired
  private MessageRepo messageRepository;

  @GetMapping("/Log")
  public String readLog(Model model){
    ArrayList<Message> messages = (ArrayList) messageRepository.findAll();
    //System.out.println(messages.length());
    model.addAttribute("messages", messages);

    return "Log";
  }


  @GetMapping("/LogWriter")
  public String getMessageInput(Model model){
    model.addAttribute("message", new Message());
    
    return "LogWriter";
  }

  @PostMapping("/LogWriter")
  public String saveMessage(@ModelAttribute Message message, Model model){
    model.addAttribute("message", message);
    messageRepository.save(message);
    return "Log";
  }


}